# format_version: 2
#
# Usage: PIPELINE_GROUP=1 NUMBER_OF_PIPES=10 python src/yamp.py examples/template01.gocd.yaml
#
pipelines:
  repeat:
    for: COUNTER
    in: {range: [1, env.NUMBER_OF_PIPES]}
    key: Hello_World_{{COUNTER}}
    body:
      label_template: ${COUNT}
      group: Group_{{ env.PIPELINE_GROUP }}
      materials:
          shared:
            git: ssh://git@bitbucket:7999/~bbirch1/gocdpocpipelines.git
      stages:
        - Hello:
            approval: success
            jobs:
              repeat:
                for: job_counter
                in: [1, 2]
                key: World{{job_counter}}
                body:
                  resources:
                    - linux
                  tasks:
                    - exec:
                        run_if: passed
                        command: /bin/bash
                        arguments:
                          - -c
                          - date

